import re

TAGALOG = set([
    "ang", "ng", "mga", "sa", "na", "ay", "at", "si", "ni", "para", "nang",
    "kung", "kapag", "pag", "dahil", "kasi", "kase", "pero", "subalit", "ngunit",
    "habang", "hanggang", "tapos", "o", "upang",
    "daw", "raw", "ba", "din", "rin", "lang", "lamang", "naman", "pala", "kaya",
    "nga", "eh", "ha", "po", "ho", "dba", "diba",
    "ako", "ikaw", "ka", "siya", "tayo", "kami", "kayo", "sila",
    "ko", "mo", "niya", "natin", "namin", "ninyo", "nila",
    "akin", "iyo", "kanya", "atin", "amin", "inyo", "kanila",
    "nito", "niyan", "niyon", "nyan", "noon", "nun",
    "ito", "iyan", "iyon", "yon", "yun", "yan",
    "dito", "diyan", "doon", "dyan",
    "nandito", "nandiyan", "nandoon", "nandto",
    "narito", "nariyan", "naroon", "kita",
    "itong", "iyong", "yong", "yung", "tong",
    "ano", "sino", "saan", "kailan", "bakit", "paano", "magkano", "ilan", "alin", "kanino", "nasaan",
    "hindi", "hinde", "di", "wala", "walang", "huwag", "wag",
    "meron", "mayroon", "may",
    "gusto", "ayaw", "alam", "kailangan", "dapat", "pwede", "puwede", "maaari",
    "sabi", "sinabi", "nagsabi", "sasabihin",
    "pumunta", "pumara", "lumabas", "pumasok", "bumalik", "umalis",
    "nakita", "makita", "makikita", "narinig", "marinig", "maririnig",
    "naintindihan", "maintindihan", "natuto", "matuto", "matutunan",
    "naging", "maging", "magiging", "nagawa", "gawin", "gagawin",
    "nagbago", "magbago", "magbabago", "nagpunta", "nagpasok", "naglabas",
    "naglaro", "maglaro", "lalaro", "nagtrabaho", "magtrabaho", "magtatrabaho",
    "nagbigay", "magbigay", "nagbayad", "magbayad", "babayaran", "bayaran", "binayad", "pinagbayaran",
    "nagkuha", "kumuha", "kukuha", "nagbenta", "magbenta",
    "nagsimula", "magsimula", "natapos", "tapusin", "matatapos",
    "nagpadala", "magpadala", "nakatanggap", "makatanggap", "tanggapin",
    "nakakain", "kumain", "kakain", "natulog", "matulog", "tutulog",
    "nagising", "gumising", "lumakad", "maglakad", "lalakad",
    "tumakbo", "magtakbo", "magpunta", "magbalik",
    "pumili", "mamili", "pinili", "nagpili", "pipili",
    "nagsalita", "magsalita", "nakinig", "makinig",
    "tumingin", "magmasid", "hinintay", "naghintay", "hintayin",
    "nagtanong", "magtanong", "tanungin", "sumagot", "sagutin", "sinagot",
    "pinayagan", "payagan", "nagpayag", "pinigilan", "pigilan", "nagpigil",
    "niluto", "magluto", "luluto", "naglinis", "maglinis",
    "pinakita", "ipakita", "nagpakita", "binabalikan", "balikan", "bumabalik",
    "pinanuod", "manood", "panoorin",
    "maganda", "ganda", "pogi", "gwapong", "gwapo",
    "malaki", "maliit", "malayo", "malapit",
    "mabuti", "masama", "mahal", "mura",
    "bago", "luma", "bata", "matanda",
    "masaya", "malungkot", "galit", "takot",
    "mainit", "malamig", "mahangin", "maulan",
    "mataas", "mababa", "mahaba", "maikli", "mataba", "payat",
    "magulo", "maayos", "malinis", "marumi",
    "madilim", "maliwanag", "maingay", "tahimik",
    "mahirap", "madali", "mapanganib", "ligtas",
    "masarap", "maanghang", "matamis", "maasim", "mapait",
    "mabilis", "mabagal", "maingat",
    "totoo", "tunay", "tama", "mali", "patas", "sigurado",
    "masipag", "tamad", "pagod", "malakas", "mahina", "matalino",
    "magaan", "mabigat", "busog", "gutom", "uhaw",
    "tao", "lalaki", "babae",
    "anak", "nanay", "tatay", "kuya", "ate", "lola", "lolo",
    "tito", "tita", "kapatid", "kaibigan",
    "bahay", "tirahan", "lugar", "lungsod", "probinsya", "bansa",
    "trabaho", "opisina", "paaralan", "simbahan", "ospital",
    "kotse", "jeep", "tren", "eroplano", "barko",
    "pagkain", "tubig", "kain", "inumin",
    "pera", "barya", "piso", "salapi",
    "oras", "minuto", "segundo", "araw", "linggo", "buwan", "taon",
    "umaga", "hapon", "gabi", "tanghali", "hatinggabi",
    "buhay", "kamatayan", "kalusugan", "sakit", "gamot",
    "puso", "isip", "kaluluwa", "katawan",
    "pangarap", "pag-asa",
    "kagalakan", "kalungkutan", "kasiyahan", "kapighatian",
    "katotohanan", "kasinungalingan", "kaalaman",
    "gobyerno", "pamahalaan", "batas", "hustisya",
    "karapatan", "kalayaan", "kapayapaan",
    "kalikasan", "kapaligiran",
    "musika", "sayaw", "awit", "sining",
    "kultura", "tradisyon", "relihiyon",
    "pilipinas", "pilipino", "filipino",
    "presyo", "halaga", "utang",
    "tanong", "sagot", "problema", "solusyon",
    "pamumuhay", "kabuhayan",
    "pamilya", "mag-asawa", "mag-anak",
    "laban", "away", "gulo", "digmaan",
    "tulong", "saklolo", "ayuda",
    "kwento", "istorya", "balita", "impormasyon",
    "larawan", "litrato", "imahe",
    "aklat", "libro", "diyaryo", "pahayagan",
    "pelikula", "palabas",
    "talaga", "talagang", "sobra", "grabe",
    "pati", "man", "sana", "sanay", "siguro", "marahil",
    "ewan", "aywan", "basta", "syempre", "siyempre",
    "ulit", "muli", "uli",
    "lagi", "palagi", "madalas", "minsan", "bihira",
    "lahat", "marami", "konti",
    "ngayon", "mamaya", "bukas", "kahapon", "maaga", "huli", "kasama",
    "ganoon", "ganun", "ganito", "ganto", "gaya",
    "parang", "prang", "mukha",
    "mas", "kaysa", "pinaka", "nalang", "nako",
    "nakaka", "nakakainis", "nakakagalit", "nakakatuwa", "nakakaawa",
    "nakakasama", "nakakabigla", "nakakagulat",
    "haha", "hahaha", "hehe", "hihi", "huhu",
    "char", "charot", "chars", "petmalu", "lods", "werpa", "lupet",
    "gigil", "kilig", "sus", "beh", "bhe", "pre", "pare", "mare", "tsong",
    "dhl", "ulet", "tlga", "cgro", "nmn", "wlang", "wla", "khit",
    "pa", "ung", "kay", "mag", "nag",
    "sya", "niyo", "sayo", "nung", "kahit", "sobrang", "muna",
    "ibang", "bossing", "nya", "galing", "nasa", "nman", "baka",
    "pinas", "ganyan", "akong", "parin", "ilang", "mong",
    "akala", "kang", "ma", "iba", "yang", "super", "hahahaha",
    "isa", "dalawa", "tatlo", "apat", "lima", "anim", "pito", "walo", "siyam", "sampu",
    "isang", "dalawang", "tatlong", "limang",
    "una", "pangalawa", "pangatlo",
    "aaral", "aasa", "agad", "ahensya", "anong", "ante", "anu", "aq", "aral",
    "asar", "asawa", "ating", "ayun", "bagay", "bagong", "bahala", "bait", "bang",
    "bangag", "bat", "batang", "bawal", "bawat", "bibig", "bilang", "bilihin",
    "buhayin", "bumuhay", "bumuo", "buong", "buti", "cla", "damay", "dami",
    "daming", "dati", "dating", "depende", "diko", "diyos", "edi",
    "epekto", "gagawa", "gamitin", "ganitong", "gasolina", "gastusin", "gatas",
    "gawa", "ginagawa", "ginawa", "gumagamit", "gumawa", "gustong",
    "hahahaa", "hahahah", "halos", "hanap", "handa", "hirap", "hnd",
    "ibig", "ibigay", "iling", "inyong", "jan", "jusko", "kaban", "kabataan", "kada",
    "kahirapan", "kakatawa", "kakayahan", "kamag", "kamo", "kana", "kanilang",
    "kanina", "kapit", "karamihan", "kasalanan", "kaso", "katulad", "kau",
    "kawawa", "kayang", "kayong", "kesa", "kesyo", "kinikita", "kng", "kong",
    "kulang", "kumita", "kundi", "laging", "lalo", "lalong", "loob", "maawa",
    "mabuhay", "madami", "madlang", "mahihirap", "mahihirapan", "makinabang",
    "makukuha", "malaking", "malala", "malaman", "maling", "marino", "masakit",
    "masyado", "mayaman", "mu", "mukhang", "mula", "mundo",
    "nahihirapan", "naka", "namang", "naming", "nangyari", "nanood", "napaka",
    "napupunta", "natawa", "nating", "nawala", "nay", "ndi", "ngang", "ngaun",
    "ngayun", "nilang", "ninakaw", "nio", "nla", "oo", "paki", "palang",
    "pambili", "pampublikong", "panahon", "pang", "pangangailangan", "pano",
    "pansin", "pantay", "panu", "papa", "papasok", "pareho", "pede",
    "pinapanuod", "puro", "ra", "realidad", "responsibilidad", "sabay",
    "sabihin", "sahod", "sakin", "sama", "sapat", "sarili", "sariling", "sasakyan",
    "saya", "sayasaya", "sen", "silang", "sinasabi", "sinasabing", "siyang",
    "sunod", "syang", "tangina", "taong", "tawa", "tawang", "tlaga", "tsk",
    "tuloy", "tutuusin", "tuwa", "ubos", "ugali", "ulo", "umasenso", "unang", "utak",
    "pinoy", "pinay", "tagalog", "noong", "tas", "nabasa", "ata", "tingin",
    "tayong", "gamit", "ganon", "totoong", "sayang", "masyadong", "dds",
    "pumasa", "nakikita", "medyo", "madaming", "labas", "tsaka", "niyang",
    "iniisip", "kapwa", "kausap", "uto", "marunong", "dahilan", "mawala",
    "babalik", "itim", "etong", "nanaman", "mahilig", "tae", "tanda",
    "bilib", "sikat", "lahi", "pwedeng", "samin", "tipong", "muka", "umiyak",
    "mamatay", "salita", "tulad", "taga", "tau", "narin", "namatay", "ama",
    "saka", "gastos", "sakanila", "aso", "ina", "umabot", "lalabas", "oa",
    "naten", "satin", "nanonood", "politiko", "kanta", "pake", "mawawala",
    "nadala", "kaba", "iyak", "gaano", "antok", "wika", "daan", "bayad",
    "pababa", "itsura", "bakla", "pangit", "puti", "nyang",
    "amo", "jowa", "ginamit", "simula", "ganyang", "demonyo", "merong",
    "madaling", "lungkot", "tinanong", "mismo", "iniwan", "tinawag", "lala",
    "naiisip", "respeto", "kumakain", "pasa", "bobo", "gumamit", "kumbaga",
    "punta", "hndi", "mang", "punto", "pinalaki", "chika", "uy",
    "kala", "dumami", "kaming", "uwi", "maisip", "nlang", "kapampangan",
    "katumbas", "ginagamit", "ingles", "plano", "talamak", "mukang",
    "baliw", "malas", "magka", "estudyante", "pambata", "swerte", "umaasa",
    "dumating", "lalaking", "pinsan", "lengwahe", "beses", "pipilitin",
    "gising", "kaagad", "tulog",
    "diskarte", "bisaya", "tampo", "sistema", "mananalo", "tungkol", "reklamo",
    "lokal", "korupsyon", "malamang", "masa", "parte", "kapangyarihan",
    "maiintindihan", "simpleng", "lagay", "presidente", "paraan", "mangyari",
    "kalaban", "kandidato", "gumagawa", "kilala", "pakialam", "tanga", "ganung",
    "negatibo", "dayuhan", "beki", "tuwing",
    "katrabaho", "lumago", "tinuturuan", "turuan", "bumoto", "bobotante",
    "padin", "bawas", "barangay", "langis", "taas", "laguna", "eto",
    "ilocano", "cebuano", "pangasinan", "capiznon", "hiligaynon", "iloilo",
    "batangas", "mindanao", "naga", "ncr",
    "mahal kita", "iniibig", "pagmamahal", "pag-ibig", "minamahal", "hinihintay",
    "naghihintay", "nakikipaglaro", "naglalaro", "nagbabasa", "nagtatrabaho",
    "naglalakad", "nagtatakbo", "nagsasayaw", "kumakanta", "nagsusulat",
    "nagdadala", "nagbibigay", "nagtatanong", "sumasagot", "nagrereklamo",
    "nagpapahinga", "nagpapalakas", "nagpapagaling", "nagpapayo",
    "susuportahan", "susuklian", "susundin", "susuriin", "sasagutin",
    "halika", "halakin", "halikayo", "huwag na", "sige na", "tara na",
    "lakad na", "kain na", "tulog na", "gawa na", "alis na",
    "naiintindihan", "naiisip", "nararamdaman", "naiinis", "nalulungkot",
    "nasasabik", "natatakot", "nahihiya", "napapagod", "namamangha",
    "nagugulat", "natutuwa", "naaawa", "nagagalit", "naiirita",
    "galak", "saya", "inis", "hiya", "takot", "pangamba", "pag-aalala",
    "pagkabigo", "pagkatalo", "tagumpay", "tagumpayan", "panalo",
    "talo", "kabigo", "subok", "pagsubok", "pagsusulit", "pagbabago",
    "pagtulong", "pagmamahal", "pagpapahalaga", "pagbibigayan",
    "magbigayan", "magtulungan", "magtulungan", "magsama-sama",
    "samahan", "kasama", "kasamamahan", "samahan mo", "samahan natin",
    "laro", "laruan", "bayani", "bayaning", "bayanihan", "malasakit",
    "pagmamalasakit", "damayan", "damayin", "kapit-bisig",
    "handa", "handang-handa", "listo", "alisto", "bantay", "bantayan",
    "ingatan", "pag-ingatan", "alagaan", "alalahanin", "isaalang-alang",
    "pag-aralan", "pag-isipan", "pagnilay", "pagbubulay",
    "biyaya", "pagpapala", "pasasalamat", "pasalamat", "salamat po",
    "walang anuman", "wala pong anuman", "tuloy po kayo", "mano po",
    "opo", "oho", "hindi po", "oo naman", "siyempre naman",
    "siguruhin", "tiyakin", "palakasin", "palawakin", "paunlarin",
    "pag-aralan", "aralin", "intindihin", "unawain", "tanggapin",
    "pagtiisan", "tiisin", "paghandaan", "maghanda", "magrehistro",
    "mag-aral", "mag-ensayo", "mag-ipon", "mamuhunan", "magtayo",
    "magtatag", "magpayo", "magbigay-diin", "magpalakas",
    "libro", "kuwaderno", "lapis", "panulat", "eraser", "ruler",
    "pisara", "silid-aralan", "guro", "titser", "propesor", "estudyante",
    "mag-aaral", "klase", "aralin", "takdang-aralin", "pagsusulit",
    "graduation", "diploma", "kurso", "kolehiyo", "pamantasan",
    "iskolar", "iskolarship", "grado", "marka", "pumasa", "bumagsak",
    "kulong", "bilangguan", "korte", "hukuman", "abogado", "pulis",
    "sundalo", "militar", "heneral", "presidente", "senador", "kinatawan",
    "alkalde", "gobernador", "kapitan", "konseho", "kongreso", "senado",
    "batas", "ordinansa", "resolusyon", "petisyon", "reklamo", "apela",
    "pagboto", "halalan", "kampanya", "pulitika", "oposisyon", "partido",
    "komunidad", "kapitbahay", "kababayan", "kababata", "kabataan",
    "mamamayan", "pagkamamamayan", "lipunan", "pamayanan",
    "simbahan", "pari", "madre", "obispo", "kardinal", "papa",
    "diyos", "panginoon", "hesus", "santa", "santo", "birhen",
    "panalangin", "misa", "rosaryo", "krus", "bibliya",
    "asin", "asukal", "paminta", "bawang", "sibuyas", "kamatis",
    "kanin", "bigas", "tinapay", "itlog", "karne", "isda", "manok",
    "baboy", "baka", "gulay", "prutas", "saging", "mangga", "niyog",
    "kamote", "patatas", "mais", "monggo", "tokwa", "toyo", "suka",
    "patis", "bagoong", "alamang", "sampalok", "sili", "luya", "gata",
    "sopas", "sabaw", "nilaga", "sinigang", "adobo", "kare-kare",
    "lechon", "kaldereta", "menudo", "afritada", "pakbet", "dinuguan",
    "halo-halo", "leche flan", "bibingka", "puto", "kutsinta",
    "palengke", "tindahan", "tiangge", "mall", "merkado", "pamilihan",
    "tindero", "tindera", "mamimili", "bumibili", "nagbebenta",
    "presyo", "diskwento", "sale", "libre", "bayad", "sukli", "resibo",
    "ospital", "klinika", "botika", "manggagamot", "nars", "doktor",
    "pasyente", "sakit", "lagnat", "sipon", "ubo", "sugat", "bali",
    "gamot", "ineksyon", "operasyon", "checkup", "laboratoryo",
    "buhay", "kalusugan", "kalikasan", "hangin", "tubig", "lupa",
    "apoy", "langit", "dagat", "ilog", "bundok", "gubat", "halaman",
    "puno", "dahon", "bulaklak", "damo", "hayop", "ibon", "isda",
    "aso", "pusa", "kabayo", "baka", "baboy", "manok", "pato",
    "palaka", "ahas", "agila", "maya", "kalapati", "uwak",
    "bituin", "buwan", "araw", "ulap", "ulan", "bagyo", "hangin",
    "lindol", "baha", "tagtuyot", "tag-ulan", "taglamig", "tag-init",
    "aparato", "armas", "arriba", "asunto", "atensyon", "ayuda",
    "balita", "bangko", "baryo", "bastardo", "bayaran", "bilya",
    "bintana", "bisita", "biyahe", "biyahin", "bodega", "bolpen",
    "boses", "boto", "butas", "byahe",
    "damit", "demonyo", "diyaryo", "doktor", "dyaryo",
    "eksamen", "eksamina", "eksena", "eksperto", "eksportasyon",
    "eleksyon", "emosyon", "empleado", "empresa", "ensayo",
    "eroplano", "eskwela", "espesyal", "estasyon", "estudyante",
    "fabrika", "familia", "fiesta", "forma", "gripo", "grupo",
    "gubernador", "gusto", "habito", "hapon", "historia", "hospital",
    "husgado", "implikasyon", "importasyon", "impormasyon",
    "indibiduwal", "industriya", "inspeksyon", "instruksyon",
    "iskandalo", "iskwela", "istasyon", "istorya", "istruktura",
    "kagawaran", "kamara", "kampanya", "kandidatura", "kapasidad",
    "kapital", "karakter", "karera", "kasaysayan", "katedral",
    "katipunan", "kolektor", "kolehiyo", "koleksyon", "komersyo",
    "komissyon", "komunidad", "koneksyon", "konstitusyon", "kontrata",
    "kontrolin", "kopya", "korapsyon", "koreksyon", "korupsyon",
    "krimen", "kultura", "kurso", "kwartero",
    "leksyon", "libreta", "lisensiyo", "lunes", "martes",
    "miyerkules", "huwebes", "biyernes", "sabado", "linggo",
    "enero", "pebrero", "marso", "abril", "mayo", "hunyo",
    "hulyo", "agosto", "setyembre", "oktubre", "nobyembre", "disyembre",
    "makina", "mapa", "medisina", "merkado", "mesa", "misa",
    "misyon", "moda", "modelo", "monumento", "musiko",
    "negosyo", "nobyo", "nobya", "nombramiento",
    "opisyal", "oportunidad", "orden", "organisasyon",
    "pakete", "palasyo", "papel", "parokyano", "partido",
    "pasahe", "pasaporte", "pastor", "pasyente", "patente",
    "patron", "pensyon", "permiso", "persona", "pelikula",
    "plano", "plataporma", "plato", "pluma", "polisiya",
    "politika", "posisyon", "presyo", "produkto", "programa",
    "proyekto", "publiko", "puwersa",
    "radyo", "rasyonal", "relihiyon", "republika", "resolusyon",
    "responsibilidad", "restawran", "resulta", "retiro",
    "sako", "saksaksyon", "salita", "serbisyo", "siglo",
    "sistema", "situasyon", "solusyon", "suporta", "suweldo",
    "taas", "tabako", "taksi", "talento", "tampisaw",
    "telebisyon", "telepono", "temperatura", "terorismo", "titulo",
    "trabaho", "tradisyon", "transaksyon", "transportasyon",
    "unibersidad", "unyon", "upisina",
    "baso", "kutsara", "tinidor", "kutsilyo", "pinggan", "palayok",
    "kawali", "kaldero", "oven", "ref", "poso", "gripo", "banyo",
    "sala", "kusina", "kwarto", "silid", "sala", "hagdan", "bakuran",
    "kotse", "bus", "trak", "motorsiklo", "bisikleta", "pedicab",
    "jeepney", "kalesa", "bangka", "barko", "eroplano", "helikopter",
    "jusko", "jusko naman", "ampota", "lods", "tropa",
    "beshie", "bestie", "besh", "bes", "teh", "chong", "idol",
    "boss", "bossing", "chief", "sis", "bro", "bruh", "brotha",
    "oy", "hoy", "oi", "ano ba", "anoh", "grabe talaga", "sana all",
    "sana ol", "feels", "feeling ko", "feel ko",
    "level up", "next level", "goals", "major goals", "life goals",
    "ship", "shipper", "shipp", "bes grabe", "grabe siya",
    "okurrr", "periodt", "valid", "valid naman", "understandable",
    "not gonna lie", "ngl", "tbh", "imo", "imho", "fyi", "asap",
    "omg", "omgg", "omfg", "lol", "lmao", "rofl", "rip",
    "fomo", "yolo", "oomf", "mutuals", "moots",
    "glow up", "glow down", "character development", "main character",
    "npc", "red flag", "green flag", "situationship",
    "ghost", "ghosted", "ghosting", "slow fade",
    "clingy", "needy", "toxic positivity", "gaslighting",
    "manifestation", "manifesting", "manifesto", "vision board",
    "hustle", "hustling", "side hustle", "girlboss", "boyboss",
    "slay", "slaying", "slayy", "slayyy", "ate slay",
    "ate girl", "kuya", "kuyang", "tol", "tols",
    "chika", "chikahin", "chismis", "chismosa", "chismoso",
    "tsismis", "tsismosa", "tsismoso", "tsika", "tsikahin",
    "kulitan", "kulitin", "kulitin mo", "kulitin natin",
    "tiis", "tiisin", "titisin", "tiis lang",
    "charge it to experience", "experience na lang",
    "it is what it is", "ganon talaga", "ganyan talaga buhay",
    "malas lang", "swertehin", "bahala na", "bahala na si batman",
    "ikaw na", "ikaw na ang magaling", "char lang",
    "joke lang", "biro lang", "half-joke", "half-serious",
    "petiks", "petix", "walang magawa", "walang gagawin",
    "tambay", "tumambay", "nagtatambay", "tambayan",
    "istambay", "istambayan",
    "nilalaro", "pinalaro", "mapapanood", "mapapanuod",
    "pang-araw-araw", "pang-umaga", "pang-gabi", "pang-hapon",
    "pangmatagalan", "panandalian", "panandaliang",
    "halimbawa", "halimba", "tulad ng", "katulad ng", "gaya ng",
    "kumpara sa", "iba sa", "kaibahan", "pagkakaiba", "pagkakatulad",
    "mas mabuti", "mas masama", "mas mababa", "mas mataas",
    "pinakamabuti", "pinakamasama", "pinakamataas", "pinakamababa",
    "aba", "abah", "aba naman", "naku", "nakuuu", "nakunaman",
    "haist", "haaay", "hay nako", "hayyy", "aray", "aray ko",
    "ouch", "aray naman", "masakit", "masakit naman",
    "kalma", "kalmahan", "calm down", "relax lang",
    "relaks", "relaks lang", "chill", "chill lang", "chillax",
    "sabihin mo sa akin", "sabihin mo lang", "ibaling mo sa akin",
    "i-share mo sa akin", "i-share mo na", "i-update mo ako",
    "i-message mo ko", "i-call mo ko", "tawagan mo ko",
    "mag-chat tayo", "mag-video call tayo", "makipag-usap",
    "kwentuhan", "kwentuhan tayo", "mag-kwentuhan",
    "araw-araw", "buwan-buwan", "taon-taon", "bawat araw",
    "minsan-minsan", "paminsan-minsan", "madalang", "mabilis na",
    "dahan-dahan", "marahan", "maingat", "maingat na",
    "nag-iisip", "nagpapaisip", "pinagisipan", "pinaghandaan",
    "nagpaplano", "nagtatago", "nagtataka", "nag-aalala",
    "nagtatalo", "nagpupumilit", "nagmamakaawa", "nagpapanggap",
    "nagpapakita", "nagpapakumbaba", "nagpapakatatag",
])

ENGLISH_CORE = set([
    "the", "a", "an", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could", "should",
    "may", "might", "must", "shall", "can", "cannot", "cant", "wont", "dont",
    "doesnt", "didnt", "wasnt", "werent", "isnt", "arent", "havent", "hasnt",
    "hadnt", "wouldnt", "couldnt", "shouldnt", "mustnt",
    "i", "you", "he", "she", "it", "we", "they", "me", "him", "her", "us", "them",
    "my", "your", "his", "its", "our", "their", "mine", "yours", "hers", "ours", "theirs",
    "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves",
    "this", "that", "these", "those",
    "what", "who", "where", "when", "why", "how", "which", "whom", "whose",
    "and", "or", "but", "if", "because", "so", "yet", "nor", "for",
    "although", "while", "since", "until", "unless", "though", "even",
    "however", "therefore", "furthermore", "moreover", "nevertheless",
    "instead", "otherwise", "meanwhile", "afterward",
    "in", "on", "at", "to", "from", "with", "by", "about", "as", "into",
    "through", "during", "before", "after", "above", "below", "between", "among",
    "against", "without", "within", "along", "across", "behind", "beyond",
    "of", "off", "up", "down", "out", "over", "under",
    "not", "no", "never", "always", "sometimes", "often", "usually",
    "all", "any", "both", "each", "few", "more", "most", "other", "some",
    "such", "than", "too", "very", "just", "also", "only", "even",
    "here", "there", "now", "then",
    "already", "still", "yet", "again", "once", "twice",
    "together", "apart", "alone", "away", "back", "forward",
    "around", "near", "far",
    "really", "truly", "actually", "basically", "literally",
    "probably", "possibly", "certainly", "definitely", "absolutely",
    "especially", "particularly", "specifically", "mainly", "mostly",
    "almost", "nearly", "quite", "rather", "fairly",
    "get", "go", "come", "see", "know", "think", "look", "want", "give",
    "use", "find", "tell", "ask", "seem", "feel", "try", "leave", "call",
    "keep", "let", "begin", "show", "hear", "play", "run", "move", "live",
    "believe", "hold", "bring", "happen", "write", "provide", "sit", "stand",
    "lose", "pay", "meet", "include", "continue", "set", "learn", "change",
    "lead", "understand", "watch", "follow", "stop", "create", "speak",
    "read", "spend", "grow", "open", "walk", "win", "offer", "remember",
    "love", "consider", "appear", "buy", "wait", "serve", "die", "send",
    "expect", "build", "stay", "fall", "cut", "reach", "remain", "suggest",
    "raise", "pass", "sell", "require", "report", "decide", "pull", "break",
    "start", "finish", "help", "work", "make", "take", "put", "place",
    "turn", "point", "become", "carry", "draw", "drive", "count", "allow",
    "add", "pick", "wear", "choose", "cause", "miss", "catch", "protect",
    "describe", "join", "push", "apply", "produce", "mark", "enter",
    "release", "manage", "achieve", "end", "prevent", "control", "accept",
    "reflect", "develop", "deal", "step", "list", "recognize", "share",
    "plan", "demonstrate", "collect", "check", "connect", "address", "agree",
    "increase", "receive", "express", "cover", "eat", "sleep", "fight",
    "drink", "talk", "subscribe", "unsubscribe",
    "watched", "worked", "loved", "moved", "called", "asked", "helped",
    "wanted", "needed", "started", "ended", "used", "tried", "liked",
    "played", "happened", "seemed", "looked", "followed", "stopped",
    "opened", "walked", "talked", "waited", "made", "came", "went", "got",
    "saw", "knew", "thought", "took", "gave", "found", "told", "left",
    "felt", "kept", "began", "showed", "heard", "brought", "lost", "paid",
    "said", "sold", "sent", "spoke", "stood", "spent", "grew", "learned",
    "changed", "led", "understood", "won", "built", "stayed", "fell",
    "cut", "reached", "remained", "suggested", "raised", "passed", "pulled",
    "broke", "finished", "put", "placed", "turned", "pointed",
    "carried", "drew", "drove", "counted", "allowed", "added", "picked",
    "chose", "caused", "missed", "caught", "described", "joined", "pushed",
    "applied", "produced", "entered", "released", "managed", "achieved",
    "prevented", "accepted", "reflected", "developed", "dealt", "collected",
    "checked", "connected", "addressed", "agreed", "increased", "received",
    "expressed", "covered", "ate", "slept", "fought", "drank", "unsubscribed",
    "watching", "working", "loving", "moving", "calling", "asking",
    "helping", "wanting", "needing", "starting", "ending", "using",
    "trying", "liking", "playing", "happening", "seeming", "looking",
    "following", "stopping", "opening", "walking", "talking", "waiting",
    "making", "coming", "going", "getting", "seeing", "knowing",
    "thinking", "taking", "giving", "finding", "telling", "leaving",
    "feeling", "keeping", "beginning", "showing", "hearing", "bringing",
    "losing", "paying", "selling", "sending", "speaking", "standing",
    "spending", "growing", "learning", "changing", "leading",
    "understanding", "winning", "building", "staying", "falling",
    "cutting", "reaching", "remaining", "suggesting", "raising",
    "passing", "pulling", "breaking", "finishing", "putting", "placing",
    "turning", "pointing", "carrying", "drawing", "driving", "counting",
    "allowing", "adding", "picking", "wearing", "choosing", "causing",
    "missing", "catching", "protecting", "describing", "joining",
    "pushing", "applying", "producing", "marking", "entering",
    "releasing", "managing", "achieving", "preventing", "controlling",
    "accepting", "reflecting", "developing", "dealing", "stepping",
    "listing", "recognizing", "sharing", "planning", "demonstrating",
    "collecting", "checking", "connecting", "addressing", "agreeing",
    "increasing", "receiving", "expressing", "covering", "eating",
    "sleeping", "fighting", "drinking", "skipping", "subscribing",
    "assuming", "attacking", "avoiding", "believing", "belonging",
    "borrowing", "camping", "cancelling", "caring", "claiming",
    "cleaning", "climbing", "closing", "coding", "competing",
    "completing", "considering", "cooking", "copying", "creating",
    "crossing", "crying", "dating", "deciding", "declaring",
    "defeating", "deleting", "delivering", "demanding", "depending",
    "deserving", "designing", "destroying", "discussing", "dismissing",
    "earning", "engaging", "enjoying", "entering", "establishing",
    "exceeding", "exchanging", "experiencing", "explaining", "exploring",
    "facing", "failing", "fearing", "feeding", "filing", "flying",
    "focusing", "forcing", "forming", "funding", "gaining", "gaming",
    "gathering", "handling", "hiring", "holding", "hoping", "hurting",
    "identifying", "ignoring", "imagining", "improving", "including",
    "informing", "inspiring", "investing", "involving", "judging",
    "keeping", "knowing", "launching", "lending", "loading", "locking",
    "logging", "matching", "meeting", "mentioning", "mixing", "naming",
    "noticing", "obtaining", "offering", "organizing", "owning",
    "performing", "posting", "preparing", "pressing", "printing",
    "processing", "promising", "proving", "pursuing", "questioning",
    "reacting", "reading", "recording", "reducing", "refusing",
    "replacing", "reporting", "requesting", "responding", "reviewing",
    "riding", "risking", "running", "saving", "searching", "setting",
    "signing", "sitting", "solving", "sorting", "storing", "streaming",
    "struggling", "submitting", "succeeding", "suffering", "switching",
    "testing", "throwing", "tracking", "trading", "transferring",
    "traveling", "treating", "typing", "updating", "uploading",
    "using", "visiting", "voting", "warning", "washing", "watching",
    "writing", "yielding",
    "good", "great", "nice", "best", "new", "old", "big", "small", "high",
    "long", "little", "own", "right", "large", "next", "early", "young",
    "important", "public", "private", "real", "different", "hard", "free",
    "true", "sure", "whole", "last", "late", "easy", "short", "clear",
    "full", "dark", "beautiful", "strong", "close", "simple",
    "happy", "sad", "bad", "wrong", "cold", "hot", "fast", "slow",
    "safe", "poor", "rich", "far", "perfect", "special", "able", "ready",
    "better", "worse", "worst", "amazing", "awesome", "terrible",
    "wonderful", "fantastic", "excellent", "incredible", "interesting",
    "boring", "exciting", "surprising", "funny", "serious", "certain",
    "current", "recent", "common", "local", "national", "international",
    "social", "political", "economic", "cultural", "physical", "mental",
    "emotional", "spiritual", "religious", "moral", "ethical", "legal",
    "official", "personal", "professional", "academic", "scientific",
    "medical", "technical", "digital", "natural", "normal", "regular",
    "general", "specific", "particular", "main", "major", "minor",
    "primary", "secondary", "basic", "advanced", "fresh", "direct",
    "extra", "single", "double", "first", "second", "third", "fourth",
    "fifth", "final", "top", "bottom", "front", "inner", "outer",
    "upper", "lower", "deep", "shallow", "wide", "narrow", "thick",
    "thin", "light", "heavy", "loud", "quiet", "soft", "rough", "smooth",
    "sharp", "dull", "clean", "dirty", "wet", "dry", "sweet", "sour",
    "bitter", "salty", "spicy", "sick", "healthy", "tired", "energetic",
    "hungry", "thirsty", "lost", "found", "broken", "fixed", "locked",
    "alive", "dead", "awake", "asleep", "surprised", "shocked", "confused",
    "worried", "scared", "angry", "excited", "bored", "interested",
    "disappointed", "frustrated", "proud", "ashamed", "guilty", "innocent",
    "jealous", "grateful", "hopeful", "hopeless", "optimistic", "pessimistic",
    "honest", "dishonest", "fair", "unfair", "correct", "incorrect",
    "accurate", "inaccurate", "complete", "incomplete", "possible",
    "impossible", "necessary", "unnecessary", "useful", "useless",
    "time", "year", "people", "way", "day", "man", "woman", "child",
    "world", "life", "hand", "part", "place", "case", "week", "company",
    "system", "program", "question", "work", "government", "number",
    "night", "point", "home", "water", "room", "mother", "area", "money",
    "story", "fact", "month", "lot", "study", "book", "eye", "job",
    "word", "business", "issue", "side", "kind", "head", "house",
    "service", "friend", "father", "power", "hour", "game", "line",
    "end", "plan", "city", "door", "car", "form", "fire", "air",
    "law", "paper", "school", "morning", "community", "body",
    "information", "phone", "video", "music", "road", "reason", "result",
    "action", "idea", "heart", "moment", "team", "group", "face",
    "voice", "name", "photo", "image", "color", "sound", "food",
    "health", "mind", "feeling", "thought", "dream", "goal", "hope",
    "fear", "pain", "joy", "peace", "freedom", "truth", "beauty",
    "strength", "courage", "wisdom", "knowledge", "skill", "talent",
    "gift", "blessing", "grace", "faith", "trust", "respect", "honor",
    "pride", "shame", "guilt", "hate", "envy", "jealousy", "greed",
    "chance", "opportunity", "choice", "decision", "option",
    "past", "future", "present", "today", "tomorrow", "yesterday",
    "afternoon", "evening", "midnight", "noon",
    "january", "february", "march", "april", "june", "july", "august",
    "september", "october", "november", "december",
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
    "north", "south", "east", "west", "center", "middle",
    "inside", "outside", "anyone", "anything", "anywhere",
    "everyone", "everything", "everywhere", "nobody", "nothing", "nowhere",
    "someone", "something", "somewhere",
    "many", "much", "enough", "plenty", "entire", "total",
    "like", "share", "post", "comment", "follow", "upload",
    "download", "stream", "channel", "content", "creator", "fan",
    "subscriber", "viewer", "feed", "timeline", "profile", "account",
    "page", "message", "chat", "reply", "mention", "tag", "hashtag",
    "picture", "selfie", "highlight",
    "thank", "thanks", "sorry", "please", "welcome", "hello", "hi", "bye",
    "yes", "okay", "ok", "sure", "wow",
    "havent", "didnt", "dont", "im", "its", "ive", "id", "ill", "theyd", "youll", "well",
    "about", "affected", "afraid", "age", "ago", "agreed", "ahead", "army",
    "aside", "aware", "become", "benefit", "blame", "cause", "change",
    "claim", "class", "clearly", "compared", "concern", "cost", "country",
    "crime", "critical", "culture", "death", "defend", "democracy", "despite",
    "difficult", "drop", "education", "effect", "elect", "election", "enjoy",
    "exact", "exist", "fail", "family", "figure", "focus", "force", "foreign",
    "forget", "friends", "fully", "fun", "further", "genuine", "genuinely",
    "given", "glad", "glory", "gold", "grade", "grants", "greater", "growth",
    "half", "happier", "hardship", "harsh", "hated", "heartbreaking",
    "heartwarming", "hell", "higher", "history", "hit", "hopefully", "host",
    "household", "human", "humor", "hurt", "idk", "imagine", "impact",
    "including", "income", "incredibly", "indeed", "independent", "industry",
    "influence", "info", "infuriating", "initially", "inspire", "inspiring",
    "interest", "internet", "interview", "issues", "jail", "jobs", "joke",
    "kickback", "kid", "kids", "kill", "killed", "kinda", "kinds", "knows",
    "lack", "later", "laugh", "laws", "leader", "least", "legit", "less",
    "level", "lie", "lies", "lifestyle", "likely", "lived", "lives", "living",
    "lmao", "logic", "longer", "looks", "loser", "lots", "low", "lowest",
    "lowkey", "luck", "luxury", "majority", "marriage", "matter", "matters",
    "maybe", "mean", "means", "meant", "media", "men", "mentality", "mentally",
    "mentioned", "messed", "military", "million", "mindset", "minimum", "mom",
    "months", "moon", "nation", "need", "network", "nevermind", "news", "ngl",
    "non", "noticed", "nuclear", "office", "officer", "oil", "ones", "online",
    "opinion", "opportunities", "opposite", "order", "others", "owned", "owner",
    "parent", "parenting", "parents", "partner", "paycheck", "payroll",
    "percentage", "personally", "physically", "plans", "pls", "points",
    "police", "politician", "politicians", "poverty", "practice", "pray",
    "pregnancy", "pregnant", "presence", "pretty", "price", "prices", "privacy",
    "privileged", "problem", "process", "proper", "prove", "proves", "puppet",
    "pursue", "quality", "questions", "rape", "rarely", "rate", "rates",
    "reality", "reasons", "recently", "reference", "regime", "region",
    "relate", "relationship", "relieved", "religion", "rely", "removed",
    "replaced", "reported", "reporting", "research", "resources", "response",
    "responsibilities", "responsibility", "restored", "results", "riches",
    "rights", "risk", "root", "routes", "salary", "save", "scholarships",
    "schools", "season", "security", "seems", "seen", "self", "senior",
    "sense", "sentiments", "sex", "shaming", "shit", "shoes", "similar",
    "simply", "sister", "sisters", "smaller", "smiling", "society", "son",
    "sorority", "source", "speaks", "sports", "spreading", "stability",
    "stable", "standard", "status", "straight", "stress", "stronger",
    "struggle", "struggles", "student", "students", "stuff", "stupid",
    "subject", "subsidy", "suffer", "suicide", "supply", "support",
    "supporting", "takes", "talks", "targeted", "tax", "taxes", "tbh",
    "teachers", "teasing", "teenage", "teens", "term", "terrorist", "thats",
    "theres", "thing", "tho", "three", "times", "title", "totally", "touched",
    "towards", "toxic", "trade", "traditional", "transport", "traumatized",
    "tricycle", "trip", "two", "uncertainty", "unfortunately", "unlike",
    "uses", "ve", "via", "vibes", "videos", "vote", "voting", "vs", "wage",
    "wake", "wants", "war", "weapon", "western", "whatever", "whenever",
    "white", "wife", "wild", "willing", "wise", "wisely", "words", "worth",
    "wtf", "younger", "youth",
    "ai", "algorithm", "analytics", "app", "application", "automation",
    "bandwidth", "blockchain", "browser", "bug", "cache", "cloud",
    "code", "coding", "cryptocurrency", "cyber", "data", "database",
    "debug", "device", "digital", "domain", "email", "encryption",
    "file", "firewall", "firmware", "framework", "frontend", "backend",
    "gpu", "hack", "hacker", "hardware", "hosting", "html", "http",
    "interface", "ip", "javascript", "keyboard", "laptop", "link",
    "linux", "login", "logout", "malware", "memory", "mobile",
    "monitor", "network", "notification", "offline", "online", "operating",
    "password", "pixel", "platform", "plugin", "privacy", "processor",
    "python", "reboot", "repository", "router", "screen", "server",
    "smartphone", "software", "spam", "startup", "storage", "tablet",
    "technology", "terminal", "token", "update", "url", "username",
    "virus", "vpn", "website", "wifi", "wireless",
    "aesthetic", "algorithm", "archive", "bio", "cancel", "cancelled",
    "collab", "content", "cringe", "crypto", "dm", "donate", "drop",
    "duet", "embed", "engage", "engagement", "exclusive", "explore",
    "fandom", "finsta", "follow", "followers", "following", "for you",
    "fyp", "going viral", "hashtag", "highlight", "hits different",
    "hype", "icon", "influencer", "irl", "it girl", "kept", "link",
    "live", "lowkey", "meme", "merch", "milestone", "minutes", "moment",
    "mood", "niche", "nostalgia", "oomf", "para social", "pin", "pinned",
    "reel", "remix", "repost", "retweet", "savage", "screenshots",
    "slaps", "stan", "stanning", "stans", "stories", "story", "swipe",
    "thread", "throwback", "tiktok", "timeline", "trending", "unfollow",
    "verify", "verified", "vibe", "viral", "vlog", "vlogger",
    "asset", "bank", "bankruptcy", "bond", "budget", "capital",
    "cash", "commodity", "consumer", "credit", "debt", "deficit",
    "deposit", "dividend", "economy", "equity", "expenditure",
    "expense", "export", "finance", "fiscal", "forex", "fund",
    "gdp", "import", "inflation", "insurance", "interest", "invest",
    "investment", "investor", "liability", "loan", "market", "mortgage",
    "mutual fund", "pension", "portfolio", "profit", "recession",
    "revenue", "savings", "shares", "stock", "surplus", "tariff",
    "tax", "trade", "transaction", "treasury", "wage", "wealth",
    "allergy", "ambulance", "anesthesia", "antibiotic", "anxiety",
    "asthma", "bacteria", "blood", "bone", "brain", "cancer",
    "cardio", "chronic", "clinic", "coma", "contagious", "depression",
    "diagnosis", "diet", "disability", "disease", "disorder",
    "dosage", "emergency", "epidemic", "exercise", "fever", "flu",
    "fracture", "genetics", "glucose", "hormone", "hygiene", "immune",
    "immunity", "infection", "inflammation", "injection", "injury",
    "insulin", "intensive", "kidney", "lung", "medication", "mental",
    "nerve", "nutrition", "obesity", "organ", "oxygen", "pandemic",
    "patient", "pharmacy", "physical", "prescription", "prevention",
    "procedure", "protein", "pulse", "quarantine", "recovery",
    "rehabilitation", "relapse", "remedy", "respiratory", "scan",
    "stomach", "surgery", "symptom", "syndrome", "therapy", "tissue",
    "treatment", "tumor", "vaccine", "virus", "vitamin", "wound",
    "assignment", "campus", "certificate", "chapter", "citation",
    "classroom", "college", "curriculum", "degree", "department",
    "dissertation", "elementary", "enrollment", "essay", "exam",
    "faculty", "fellowship", "field", "grade", "graduate", "grant",
    "high school", "institute", "laboratory", "lecture", "library",
    "master", "module", "nursery", "objective", "oral", "peer",
    "professor", "project", "publish", "quiz", "reading", "research",
    "review", "scholarship", "semester", "seminar", "subject",
    "syllabus", "term", "test", "thesis", "topic", "tutor",
    "undergraduate", "university", "workshop", "written",
    "attachment", "authentic", "awareness", "boundary", "boundaries",
    "burnout", "cathartic", "closure", "coping", "detachment",
    "empath", "empathy", "empowerment", "entitlement", "exhausted",
    "healing", "healthy", "imposter", "inner child", "insecure",
    "introspection", "invalidate", "journal", "journaling",
    "love language", "love languages", "loyalty", "manipulation",
    "maturity", "minimize", "narcissist", "narcissistic", "neglect",
    "overthinking", "prioritize", "projection", "protect", "reactive",
    "resilience", "resilient", "self-care", "self-worth", "setting",
    "shame", "spiral", "therapy", "toxic", "trauma", "trigger",
    "triggered", "validate", "validation", "vulnerable", "vulnerability",
])


def is_tagalog(token):
    t = token.lower()
    if t in TAGALOG:
        return True
    tagalog_prefixes = (
        'nag', 'mag', 'pag', 'naka', 'maka', 'pinag', 'ipag',
        'nakaka', 'nakakaing', 'nagka', 'nagpa', 'magpa',
        'napapalab', 'napa', 'maipa', 'naipa', 'maipag', 'naipag',
        'mapag', 'napag', 'makipag', 'nakikipag',
        'pakikipag', 'pina', 'pinaka', 'makapag', 'nakapag',
        'pagka', 'pagkaka', 'pagpapa',
    )
    for prefix in tagalog_prefixes:
        if t.startswith(prefix) and len(t) > len(prefix) + 2:
            return True
    return False


def is_english(token):
    t = token.lower()
    if t in ENGLISH_CORE:
        return True
    if is_tagalog(token):
        return False
    english_suffixes = ('tion', 'sion', 'ness', 'ment', 'ful', 'less',
                        'ify', 'ize', 'ise', 'ous', 'ious', 'ive', 'ative',
                        'ible', 'able', 'ical', 'ish')
    for suffix in english_suffixes:
        if t.endswith(suffix) and len(t) > len(suffix) + 2:
            return True
    return False


def tokenize(text):
    text = re.sub(r'\[PERSON\]', '', text)
    emoji_pattern = re.compile(
        u'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF'
        u'\U0001F1E0-\U0001F1FF\U00002702-\U000027B0\U000024C2-\U0001F251'
        u'\U0001f926-\U0001f937\U00010000-\U0010ffff\u2640-\u2642'
        u'\u2600-\u2B55\u200d\u23cf\u23e9\u231a\ufe0f\u3030\u2764\u2665'
        u'\u2666\u2663\u2660\u2661\u2662\u2663\u2764\u2665\u2661\u2662'
        u'\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF]+',
        flags=re.UNICODE)
    text = emoji_pattern.sub('', text)
    text = text.replace('\u2019', "'").replace('\u2018', "'")
    tokens = text.split()
    result = []
    for token in tokens:
        clean = re.sub(r"[^\w']", '', token)
        clean = re.sub(r"'s$", '', clean)
        clean = re.sub(r"^'+|'+$", '', clean)
        if not clean:
            continue
        if re.match(r'^\d+$', clean):
            continue
        if not re.search(r'[a-zA-Z]', clean):
            continue
        if len(clean) == 1 and clean.lower() not in ('a', 'i', 'o'):
            continue
        result.append(clean)
    return result


def compute_csd(tokens):
    if not tokens:
        return 0.0
    english_count = sum(1 for t in tokens if is_english(t))
    return round(english_count / len(tokens), 4)


def get_density_band(csd: float) -> str:
    if csd <= 0.20:
        return "Band 1 (0–20%): Tagalog-dominant"
    elif csd <= 0.40:
        return "Band 2 (21–40%): Mostly Tagalog"
    elif csd <= 0.60:
        return "Band 3 (41–60%): Balanced Taglish"
    elif csd <= 0.80:
        return "Band 4 (61–80%): Mostly English"
    else:
        return "Band 5 (81–100%): English-dominant"


def get_language_type(csd: float) -> str:
    if csd > 0.80:
        return "English"
    elif csd < 0.20:
        return "Tagalog"
    else:
        return "Taglish"


def compute_density(text: str) -> tuple:
    """Public API: Returns (csd_float, band_label, language_type, token_count)"""
    tokens = tokenize(text)
    csd = compute_csd(tokens)
    band = get_density_band(csd)
    lang_type = get_language_type(csd)
    return csd, band, lang_type, len(tokens)


def detect_emoji(text: str) -> tuple:
    """Returns (has_emoji, count)"""
    try:
        import emoji as emoji_lib
        count = emoji_lib.emoji_count(text)
        return count > 0, count
    except ImportError:
        emoji_pattern = re.compile(
            u'[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF'
            u'\U0001F1E0-\U0001F1FF\U00002702-\U000027B0]+',
            flags=re.UNICODE)
        matches = emoji_pattern.findall(text)
        return len(matches) > 0, len(matches)